/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "primary-container": "#4d8eff",
        "secondary-fixed": "#ffdbca",
        "on-secondary-fixed": "#341100",
        "inverse-on-surface": "#2c303d",
        "surface-container-lowest": "#0a0e1a",
        "on-secondary-fixed-variant": "#783200",
        "on-secondary": "#552100",
        "primary-fixed": "#d8e2ff",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary-container": "#5c0008",
        "tertiary": "#ffb3ad",
        "outline-variant": "#424754",
        "surface-variant": "#313442",
        "on-tertiary-fixed-variant": "#930013",
        "secondary-fixed-dim": "#ffb690",
        "error": "#ffb4ab",
        "on-surface": "#dfe2f3",
        "on-error-container": "#ffdad6",
        "on-primary": "#002e6a",
        "outline": "#8c909f",
        "secondary-container": "#ec6a06",
        "surface-container-highest": "#313442",
        "on-primary-container": "#00285d",
        "inverse-surface": "#dfe2f3",
        "surface-container-high": "#262a37",
        "surface-bright": "#353946",
        "inverse-primary": "#005ac2",
        "surface-container-low": "#171b28",
        "on-tertiary-fixed": "#410004",
        "on-background": "#dfe2f3",
        "background": "#0f131f",
        "primary-fixed-dim": "#adc6ff",
        "on-error": "#690005",
        "error-container": "#93000a",
        "secondary": "#ffb690",
        "surface-container": "#1b1f2c",
        "surface": "#0f131f",
        "primary": "#adc6ff",
        "on-secondary-container": "#4a1c00",
        "on-tertiary": "#68000a",
        "tertiary-container": "#ff5451",
        "on-primary-fixed-variant": "#004395",
        "tertiary-fixed": "#ffdad7",
        "surface-dim": "#0f131f",
        "tertiary-fixed-dim": "#ffb3ad",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
