import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { HeatMap } from "./components/HeatMap";
import { MetricCard } from "./components/MetricCard";
import { useDashboardSession } from "./hooks/useDashboardSession";
import { ms, pct, time } from "./utils/format";
export function App() {
    const { sessionId, connected, attempts, makes, misses, fgPct, avgLatency, avgFormScore, currentStreak, bestStreak, zones, feed, error, setSessionId, canJoin, createAndJoinSession, joinSession, disconnect, } = useDashboardSession();
    function handleJoin(event) {
        event.preventDefault();
        joinSession();
    }
    return (_jsxs("main", { className: "page", children: [_jsxs("header", { className: "hero", children: [_jsxs("div", { children: [_jsx("h1", { children: "CourtVision Live Dashboard" }), _jsx("p", { children: "WebSocket-powered shooting analytics and court heat mapping" })] }), _jsx("div", { className: `status ${connected ? "ok" : "off"}`, children: connected ? "Connected" : "Disconnected" })] }), _jsxs("section", { className: "controls", children: [_jsxs("form", { onSubmit: handleJoin, children: [_jsx("label", { htmlFor: "session", children: "Session ID" }), _jsx("input", { id: "session", value: sessionId, onChange: (e) => setSessionId(e.target.value), placeholder: "Paste session UUID" }), _jsxs("div", { className: "button-row", children: [_jsx("button", { type: "submit", disabled: !canJoin, children: "Join Session" }), _jsx("button", { type: "button", className: "secondary", onClick: createAndJoinSession, children: "Create Session" }), _jsx("button", { type: "button", className: "danger", onClick: disconnect, children: "Disconnect" })] })] }), error ? _jsx("p", { className: "error", children: error }) : null] }), _jsxs("section", { className: "metrics-grid", children: [_jsx(MetricCard, { label: "Attempts", value: `${attempts}` }), _jsx(MetricCard, { label: "FG%", value: pct(fgPct) }), _jsx(MetricCard, { label: "Make / Miss", value: `${makes} / ${misses}` }), _jsx(MetricCard, { label: "Avg Inference", value: ms(avgLatency) }), _jsx(MetricCard, { label: "Form Score", value: pct(avgFormScore) }), _jsx(MetricCard, { label: "Current Streak", value: `${currentStreak}` }), _jsx(MetricCard, { label: "Best Streak", value: `${bestStreak}` })] }), _jsxs("section", { className: "content-grid", children: [_jsx(HeatMap, { zones: zones }), _jsxs("section", { children: [_jsx("h2", { children: "Recent Shot Feed" }), _jsxs("div", { className: "feed-list", children: [feed.length === 0 ? _jsx("p", { className: "feed-empty", children: "No live shot events yet." }) : null, feed.map((event) => (_jsxs("article", { className: "feed-item", children: [_jsxs("p", { children: [_jsx("strong", { children: event.result.toUpperCase() }), " at ", time(event.timestamp_ms)] }), _jsxs("p", { children: ["Conf ", (event.confidence * 100).toFixed(1), "% | Latency ", event.inference_latency_ms.toFixed(0), "ms | Form ", (event.form_score ?? 0).toFixed(1), "%"] }), _jsxs("p", { children: ["Zone: ", event.zone.replace(/_/g, " "), " | Pose: elbow ", (event.elbow_angle_deg ?? 0).toFixed(1), "\u00B0, knee ", (event.knee_angle_deg ?? 0).toFixed(1), "\u00B0, torso ", (event.torso_tilt_deg ?? 0).toFixed(1), "\u00B0"] })] }, `${event.timestamp_ms}-${event.result}`)))] })] })] })] }));
}
